#!/usr/bin/env python3
"""Tier-2 task D0.1 — overlay memory map, with mode identification.

Emits docs/research/Overlay-Map.md.

The plan sketched parsing `ftc/y9.bin`. This reads the overlay table straight out
of the ROM header instead, which is equivalent and doesn't depend on the extracted
filesystem being present:

    header 0x50 -> arm9 overlay table offset, length   (32 bytes per entry)
    header 0x48 -> FAT offset, length                  (8 bytes per file)

On top of the raw map it identifies each overlay's *mode* by counting references to
the ROM's asset directory names in the overlay's strings. That matters because ten
of the fourteen overlays share load address 0x0214CD20, so an address alone never
tells you which code is resident.

Read-only. Falls back to jus_files/overlays/ if the ROM isn't present.
"""

from __future__ import annotations

import argparse
import collections
import re
import struct
import sys
from pathlib import Path

DEFAULT_ROM = Path("/Users/djdjo/Documents/mine/rom/jus.nds")
OVERLAY_DIR = Path("jus_files/overlays")
OUT = Path("docs/research/Overlay-Map.md")

# Asset directories in the ROM filesystem double as the mode vocabulary.
ASSET_DIRS = [
    "battle", "ChildRom", "Common", "Commu", "database", "deckcheck", "deckmake",
    "deckselect", "demo", "dwc", "efc", "ending", "font", "ftc", "info", "input",
    "item", "JArena", "jgalaxy", "jpower", "jquiz", "koma", "opening", "option",
    "result", "ruleselect", "sound", "stage", "title", "tutorial",
]

# Mode labels, keyed by the dominant directory reference. Derived from the counts
# this script produces; see docs/research/Overlay-Map.md for the reasoning.
MODE_BY_DOMINANT = {
    "ending": "Boot / title / opening / ending / options",
    "result": "Deck **select** list + results screens",
    "demo": "J Galaxy (story mode) + demos",
    "JArena": "J Arena",
    "jquiz": "J Quiz",
    "database": "**Deck Make (the editor itself)** + koma browser / database",
    "battle": "Battle",
    "Commu": "Local wireless multiplayer",
    "dwc": "Nintendo WFC (online)",
    "info": "Shared in-game support (HUD, stage, item)",
}

# Residency measured by byte-comparing each overlay against live emulator RAM
# (harness session). Only modes actually visited are listed.
MEASURED_RESIDENCY = {
    1: "confirmed resident on the deck-SELECT screen (99.8%)",
    6: "confirmed resident in battle (100%)",
    10: "confirmed resident in the deck-select screen (100%)",
    11: "confirmed resident in battle (100%)",
    12: "resident in BOTH battle and deck screens (100% deck, 59.6% battle — the "
        "lower figure is runtime mutation of its writable data, not a different overlay)",
}

STR_RE = re.compile(rb"[\x20-\x7e]{4,}")


def read_table(rom: bytes) -> list[dict]:
    ovt_off, ovt_len = struct.unpack_from("<II", rom, 0x50)
    fat_off, _ = struct.unpack_from("<II", rom, 0x48)
    out = []
    for i in range(ovt_len // 32):
        e = ovt_off + i * 32
        ov_id, ram, size, bss, si_s, si_e, file_id, packed = \
            struct.unpack_from("<IIIIIIII", rom, e)
        start, end = struct.unpack_from("<II", rom, fat_off + file_id * 8)
        out.append({
            "id": ov_id, "ram": ram, "size": size, "bss": bss,
            "rom_start": start, "rom_end": end,
            "compressed": packed >> 24,
        })
    return out


def identify(data: bytes) -> tuple[dict, list[str]]:
    strings = [s.decode("ascii", "ignore") for s in STR_RE.findall(data)]
    blob = " ".join(strings).lower()
    hits = collections.Counter()
    for d in ASSET_DIRS:
        n = blob.count(d.lower())
        if n:
            hits[d] = n
    files = sorted({
        s for s in strings
        if re.search(r"\.(bin|aar|dtx|dig|atm|ncl|nce|nsc)$", s, re.I) and len(s) > 5
    })
    return hits, files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--rom", type=Path, default=DEFAULT_ROM)
    ap.add_argument("--overlays", type=Path, default=OVERLAY_DIR)
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    if not args.rom.exists():
        print(f"ROM not found: {args.rom}", file=sys.stderr)
        return 1
    rom = args.rom.read_bytes()
    entries = read_table(rom)

    # group by load address so the mutual-exclusion sets are obvious
    by_addr = collections.defaultdict(list)
    for e in entries:
        by_addr[e["ram"]].append(e)

    L = []
    L.append("# Overlay Memory Map")
    L.append("")
    L.append("Generated by `scripts/decomp/overlay_map.py` (Tier-2 task D0.1). Read-only; "
             "regenerate any time.")
    L.append("")
    L.append(f"**{len(entries)} ARM9 overlays.** All uncompressed, so for a resident overlay "
             "`file_offset = runtime_addr - ram_address`.")
    L.append("")
    L.append("The critical fact: overlays are grouped by load address and **overlays sharing an "
             "address are mutually exclusive**. An address alone never identifies code — you also "
             "need to know which overlay is resident. Any watchpoint or address citation in a "
             "shared window must name the expected overlay.")
    L.append("")

    for addr in sorted(by_addr):
        grp = by_addr[addr]
        L.append(f"## Load address `0x{addr:08X}` — {len(grp)} overlay"
                 f"{'s' if len(grp) > 1 else ''}, mutually exclusive")
        L.append("")
        L.append("| ov | size | bss | ROM range | mode (from string analysis) | residency |")
        L.append("|---|---|---|---|---|---|")
        for e in sorted(grp, key=lambda x: x["id"]):
            f = args.overlays / f"ov{e['id']:02d}.bin"
            if f.exists() and e["size"] > 1000:
                hits, _ = identify(f.read_bytes())
                dom = hits.most_common(1)[0][0] if hits else "?"
                mode = MODE_BY_DOMINANT.get(dom, f"unclassified (top ref: {dom})")
                top = ", ".join(f"{k}×{v}" for k, v in hits.most_common(4))
            elif e["size"] <= 1000:
                mode, top = "stub", "—"
            else:
                mode, top = "not extracted", "—"
            res = MEASURED_RESIDENCY.get(e["id"], "not measured")
            L.append(f"| **ov{e['id']:02d}** | {e['size']:,} | {e['bss']:,} | "
                     f"`0x{e['rom_start']:X}`–`0x{e['rom_end']:X}` | {mode} | {res} |")
        L.append("")
        L.append("<details><summary>top asset-directory references per overlay</summary>")
        L.append("")
        for e in sorted(grp, key=lambda x: x["id"]):
            f = args.overlays / f"ov{e['id']:02d}.bin"
            if f.exists() and e["size"] > 1000:
                hits, files = identify(f.read_bytes())
                L.append(f"- **ov{e['id']:02d}**: "
                         + ", ".join(f"`{k}`×{v}" for k, v in hits.most_common(6)))
                if files:
                    L.append(f"  - e.g. {', '.join('`'+x+'`' for x in files[:5])}")
        L.append("")
        L.append("</details>")
        L.append("")

    L.append("## Notes")
    L.append("")
    L.append("- **ov05 is the deck editor proper**, not ov01. ov05 references `deckmake`, "
             "`database`, `koma` and `input` (the kana keyboard for naming a deck); ov01 "
             "references `deckselect` and `result`. So ov01 is the deck *list* screen and ov05 is "
             "the editing screen. This resolves an apparent conflict: the nature resolver at "
             "`0x0214E480` is in ov05, while RAM measured on the deck-select screen showed ov01.")
    L.append("- **ov11 is battle AI** — it is the only overlay referencing `chr/ai/ai_param.bin`.")
    L.append("- **ov12 is shared support code**, resident across both battle and deck screens.")
    L.append("- ov09 and ov13 are 32-byte stubs.")
    L.append("- Mode labels come from counting asset-directory references in each overlay's "
             "strings. That is strong evidence but not proof; the five entries marked "
             "*confirmed resident* were verified by byte-comparing the overlay against live RAM.")
    L.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(L) + "\n")
    print(f"wrote {args.out} ({len(entries)} overlays)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
